### ISSUE TITLE
No email by template sent if from is empty

### ISSUE THREAD

**Issue by dmush** [mailjet/mailjet-apiv3-nodejs#38]
Hi,

Faced an issue with transactional emails. When I send an email with non-empty 'TemplateID' and empty 'From' I get the 200 OK response but no email on my mailbox. But all works as expected for the same setup and non-empty 'From' property.

This code doesn't work.
```javascript
require('node-mailjet').connect('...', '...')
  .post('send', {'version': 'v3.1'})
  .request({
    Messages: [
      {
        To: [
          {
            Email: '...',
            Name: '...'
          }
        ],
        TemplateID: ...,
        TemplateLanguage: true,
        Variables: {
          ...
        }
      }
    ]
  })
```

But the same with 'From' works. Email, Name and Subject are set for the template.

Thanks!

**Comment by latanasov** [comment]
Hi @dmush , unfortunately it seems that we have a bug in the API itself. Please set the From property for the moment, while we work on fixing it.
Thank you for reporting the issue !

**Comment by maganap** [comment]
Is there any plan to fix this? I have different senders by template, and having those in the source code is not a practical option.

**Comment by clemlucasynotek** [comment]
Same issue... Any fixes soon ?

**Comment by thaitzer** [comment]
still not fixed.
My current workaround: querying the API for the sender and subject - then sending it back to the api

**Comment by eilgin** [comment]
**1 year after**, the bug still exists!
Could you fix this issue as your docs specifically state that we can rely on the "From" info given in the template if the "From" wasn't explicitely set?

**Comment by quezak** [comment]
Unless you plan to fix this soon, it should at least be documented. I just came here after I wanted to post the same issue myself, after a day of trial-and-error query debugging.

It's really unacceptable that the API returns `200 OK` with the message ids and everything, but then `GET /v3/REST/message/{MessageID}` returns `404 NOT FOUND`.

**Comment by fossejc** [comment]
Hi all,

This bug is a must have on my side. Having the email addresses in the source code is not an option.

**Comment by todorDim** [comment]
Hello all,

This is something we've taken into account. We'll update the README documentation and address it internally. 

Regards,
T.

**Comment by VitaliiZhukov** [comment]
Hi there,
is it an API v3.1 issue or only this specific 'nodejs' package problem?

**Comment by kmanchikov** [comment]
Hey guys, 

This is now resolved, and Send API V3.1 is fixed to handle the FromEmail and FromName declared in the Template, without needed to be declared in the Send API Call as well.

**Comment by thaitzer** [comment]
While I already wrote you a ticket, I will just inform the public here as well. This update does *not* include the REPLY-TO field. This has still the same issue.

**Comment by amonkonanBYF** [comment]
use process.env.MJ_APIKEY_PUBLIC and use process.env.MJ_APIKEY_PRIVATE 
instead of code string when you 
`require('node-mailjet').connect`

**Comment by ngarnier** [comment]
Closing as fixed in May 2019 as indicated by @kmanchikov.
